runtime: nodejs12

service: marvel-heroes

instance_class: F1

automatic_scaling:
  max_concurrent_requests: 20
  min_idle_instances: 0
  max_pending_latency: 300ms

default_expiration: "1s" #365d

handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
  secure: always
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always